services:
  pocketbase:
    build: ./pb
    container_name: bunkerlink-pocketbase
    restart: unless-stopped
    healthcheck: 
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default_network
    volumes:
      - ./pb/pb_data:/pb/pb_data

  nginx:
    image: "nginx:latest"
    container_name: bunkerlink-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8090:80"
    depends_on:
      - pocketbase
    networks:
      - default_network


networks:
  default_network: